### ISSUE TITLE
TightVNC doesn't run 'rect' event

### ISSUE THREAD

**Issue by blandman** [sidorares/node-rfb2#12]
I'm wanting to use TightVNC with rfb2. Rfb2 works great with RealVNC (besides cursor is black box, not a priority at the moment).

I tried using Wireshark to sniff the packets going back and forth and I couldn't determine what the issue is. Using another VNC client worked to get the screen from TightVNC, but Tight seems to not emit the 'rect' event at all, even after doing a requestUpdate. Keyboard and mouse events work fine.

My question is there another event that could be listened to for TightVNC to send the screen?

I'll continue working with RealVNC for now as I build my web interface, but it would be fantastic to get TightVNC working properly. As I work for a public school district and money is *tight*.

**Comment by blandman** [comment]
I read from issue #3 that it has only ben tested with TightVNC so I must be doing something wrong. I'll reinstall TightVNC to see if maybe it is a config I have set.

**Comment by sidorares** [comment]
I tried to install tightvncserver on ubuntu 14.10 and then opened using https://github.com/sidorares/node-x11/blob/master/examples/vncviewer/vncgui.js client and everything works as expected. Can you describe your configuration a bit more? ( e.i how do you start server, if you are using compositing window manager etc)

**Comment by blandman** [comment]
Sorry for the delay. First off thanks for that vncgui script, after reading it I imagine it has good performance. Later today I will be doing more testing, I'll try that x11 server on the same TightVNC install then re-install TightVNC. I am using http://blog.mgechev.com/2013/08/30/vnc-javascript-nodejs/ as the base of my node server. I've modified it slightly to use JPEG instead of PNG for performance, and have added more event listeners from my socket.io web client. TightVNC didn't work before I made my modifications though.

I am trying to use TightVNC server on 64bit Windows 7 as a service, I've gone over the configs a few times and can't find anything that really pops out as needing to be changed. I won't be able to get to working on this again for at least a few hours, so when I get a chance to test I'll post another comment. Thank @sidorares for your help.

**Comment by blandman** [comment]
I was never able to get TightVNC working.

I ended up settling on Ultra VNC, got it deployed with group policy, then came back to this. Initially UltraVNC would load 1 frame, then go black. After setting the requestUpdate function  boolean to true from false, I was getting an image.

Thanks for your work on this library, it is a game changer.

**Comment by yeya** [comment]
Please reopen the issue, TightVNC on Windows doesn't fire `rect` events
