### ISSUE TITLE
Remote cursor shape

### ISSUE THREAD

**Issue by Madd0g** [sidorares/node-rfb2#24]
I did some googling and it seems like some RFB clients support remote cursor shape.  I mean when the cursor shape changes on the server to something like resize or text, I want to receive that event on the client.

Is that currently supported or planned?

Thanks

**Comment by sidorares** [comment]
hi! Not supported, but I'm happy to add it ( no promise on timing though if I do it myself )

looks relatively simple - [Cursor Pseudo-Encoding](https://tools.ietf.org/html/rfc6143#section-7.8.1)

**Comment by sidorares** [comment]
hi @Madd0g - added and published as @v0.1.0

api: rect with encoding set to rfb.encodings.pseudoCursor. rect.data = same as raw rectangle ( cursor visible pixels ) rect.mask - bitmap, mask ( one bit per pixel ). rect.x, rect.y - cursor hostspot location

When this is enabled at connection time server does not display cursor, but sends cursor update events ( as rectangles with pseudoCursor encoding ) each time cursor shape is changed
